# Generated by Django 4.1.1 on 2022-12-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_alter_hospital_users_e_mail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blood_stock',
            name='District',
            field=models.CharField(default='district', max_length=30),
        ),
    ]
