# Generated by Django 4.1.1 on 2022-11-12 07:39

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blood_Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=30)),
                ('E_mail', models.EmailField(max_length=50)),
                ('PH_number', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('Password', models.CharField(max_length=30)),
            ],
        ),
    ]
