# Generated by Django 4.1.1 on 2022-11-14 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blood_Donor_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=30)),
                ('Age', models.PositiveIntegerField()),
                ('Blood_Type', models.CharField(max_length=3)),
                ('Date_Of_Birth', models.DateField()),
                ('Gender', models.CharField(max_length=10)),
                ('Address1', models.CharField(max_length=1024)),
                ('Address2', models.CharField(max_length=1024)),
                ('PinCode', models.CharField(max_length=8)),
                ('State', models.CharField(max_length=15)),
                ('Weight', models.FloatField(max_length=6)),
                ('Diabetic', models.CharField(max_length=5)),
                ('HIV', models.CharField(max_length=5)),
                ('Medicine', models.CharField(max_length=5)),
                ('Medicine_Name', models.CharField(max_length=30, null=True)),
                ('Disease', models.CharField(max_length=5)),
                ('Disease_Name', models.CharField(max_length=30, null=True)),
                ('Surgery', models.CharField(max_length=5)),
                ('Surgery_Name', models.CharField(max_length=30, null=True)),
                ('Donated_Previous', models.CharField(max_length=5)),
                ('Donated_Date', models.DateField(null=True)),
                ('Blood_User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donor.blood_users', null=False)),
            ],
        ),
    ]
