# Generated by Django 4.1.1 on 2022-11-26 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood_donor_register',
            name='Blood_User',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='donor.blood_users'),
        ),
    ]
