# Generated by Django 4.1.1 on 2022-12-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_alter_blood_users_e_mail_alter_blood_users_ph_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blood_donor_register',
            old_name='Address1',
            new_name='Address',
        ),
        migrations.RemoveField(
            model_name='blood_donor_register',
            name='Address2',
        ),
        migrations.AddField(
            model_name='blood_donor_register',
            name='Hospital',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
