# Generated by Django 4.1.1 on 2022-11-14 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_blood_donor_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blood_donor_register',
            name='Blood_User_id',
        ),
    ]
