# Generated by Django 4.1.1 on 2022-12-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_rename_address1_blood_donor_register_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood_donor_register',
            name='Date_Of_Birth',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='blood_donor_register',
            name='Donated_Date',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
