# Generated by Django 4.1.1 on 2022-11-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0008_alter_blood_donor_register_blood_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blood_donor_register',
            name='District',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
